name: 'setup base env'
description: "setup base environment for build tegola"
inputs:
  ui:
    description: 'Download UI'
    required: false
    default: 'false'
  go:
    description: 'Download install go'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download version artifact
      uses: actions/download-artifact@v1
      with:
        name: version

    - name: Download ui artifact
      uses: actions/download-artifact@v1
      with:
        name: ui
        path: ${{ github.workspace }}/ui/dist
      if: ${{ inputs.ui == 'true' }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      if: ${{ inputs.go == 'true' }}

    - name: Set tegola version
      run: go run ci/cat_version_envs.go -version_file version/version.txt | tee $GITHUB_ENV
      shell: bash

    - name: Download default-branch-ref artifact
      uses: actions/download-artifact@v1
      with:
        name: default-branch-ref

    - name: Set tegola default branch ref
      run: echo "DEFAULT_BRANCH_REF=$(cat default-branch-ref/default-branch-ref.txt)" >> $GITHUB_ENV
      shell: bash

    - name: Say goodbye
      run: echo "goodbye! ${{ runner.os }} ${{ runner.arch }}"
      shell: bash

